# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name          = "feeling_rusty"
  spec.version       = "0.1.0"
  spec.authors       = ["feeling-rusty contributors"]
  spec.summary       = "Ruby bindings for feeling-rusty (UniFFI)"
  spec.description   = "Ruby bindings for the feeling-rusty Rust library generated by UniFFI."
  spec.homepage      = "https://github.com/jacksonporter/feeling-rusty"
  spec.license       = "MIT"
  spec.required_ruby_version = ">= 3.0"
  spec.files         = Dir["lib/**/*"].reject { |f| f.end_with?(".gitkeep") }
  spec.require_paths = ["lib"]
  spec.add_runtime_dependency "ffi", "~> 1.15"
end
